### ISSUE TITLE
要扩展支持一般自定义cell的动态高度

### ISSUE THREAD

**Issue by yisRookie** [MaricleZhang/LMForm#1]

**Comment by MaricleZhang** [comment]
你好，LMForm是支持cell动态高度的.你可以先计算好高度，传给model.height.

**Comment by yisRookie** [comment]
这个我知道，我的意思是 是不是可以加个 UITableViewAutomaticDimension这个呢~

**Comment by MaricleZhang** [comment]
可以的哥们，我们可以一起想一下实现方案。
